### ISSUE TITLE
Works but switches back...

### ISSUE THREAD

**Issue by naylin-mi** [sean6541/tuya-homeassistant#1]
I have followed all your instructions and got this up and running! YAY! Switched on my lamp and it came on! YAY again! But then the switch in home assistant switched back to off. The light stayed on but the switch in home assistant was off. 

I'm guessing that there is something buggy in the way it reports the status to home assistant. If I go to states and manually set the state, the switch stays where it's supposed to (doesn't actually turn on or off the swich just sets the state of the switch) but not when I "flip" the switch.

I will provide any information that you might need to help to fix this since I'm very excited to have this working for my Tuya switches!

~Naylin

**Comment by sean6541** [comment]
Are there any connection errors related to tuya.py in the home assistant logs? The might look like: "Failed to update status."

**Comment by sean6541** [comment]
I have recently been making changes to the way the switch status is reported.

**Comment by sean6541** [comment]
Until I get it working you can always use commit 7e5acde.

**Comment by naylin-mi** [comment]
This is what I get in the logs after switching it on:

`Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/tuya.py", line 77, in update
    status = self._device.status()
  File "/srv/homeassistant/lib/python3.5/site-packages/pytuya/__init__.py", line 221, in status
    result = json.loads(result)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
2018-01-10 10:36:21 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.plug_1 fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/tuya.py", line 77, in update
    status = self._device.status()
  File "/srv/homeassistant/lib/python3.5/site-packages/pytuya/__init__.py", line 221, in status
    result = json.loads(result)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
`

Hope that helps! :)
Btw: I'm using these switches with this: [http://www.amazon.com/gp/product/B0713SKWQ1](url)
so you know that another one will work as well as any others that have been tested.

**Comment by naylin-mi** [comment]
sorry, I didn't know that "close and comment would close the issue.

**Comment by sean6541** [comment]
I and a few others are working on resolving the `JSON object must be str, not 'bytes'` issue. Others are having the same issue as you but I am not having the issue. I think it has to do with the version of Python being used.

**Comment by naylin-mi** [comment]
It's great to hear that you guys are working on the issue, and (in a way) that I'm not the only one experiencing it. In the meantime, I'm using the commit that you linked above and it's working well with one small caveat, that I can live with for a while. It doesn't report the status of the switch when I restart Home Assistant. So Home Assistant thinks that they are all off. Small thing and I'm sure that this might be one of the reasons that you're re-doing the script.

**Comment by sean6541** [comment]
I think nijave and clach04 got it working. Try using the latest version.

**Comment by naylin-mi** [comment]
Still doesn't work for me.

`2018-01-13 08:31:26 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.living_room_lamp fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/tuya.py", line 76, in update
    status = self._device.status()
  File "/srv/homeassistant/lib/python3.5/site-packages/pytuya/__init__.py", line 246, in status
    result = json.loads(result)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'`

**Comment by slomanl1** [comment]
There has been an update published to [https://github.com/clach04](url) that may partially address the problem.

**Comment by sean6541** [comment]
Thanks slomanl1, i updated the platform to use the latest version of [https://github.com/clach04/python-tuya](https://github.com/clach04/python-tuya)

**Comment by sean6541** [comment]
I can't seem to reproduce the `TypeError: the JSON object must be str, not 'bytes'` error, so go ahead an try it.

**Comment by slomanl1** [comment]
Sean I do not see how your change to your tuya.py incorporates any changes from clach04. All you did was change the requirements number from 2.0 to 3.0. clach04 has changes in __init__.py. How does your code pick those up?

**Comment by sean6541** [comment]
HA requires that dependencies are hosted on pypi, so i keep a copy of the [https://github.com/clach04/python-tuya](https://github.com/clach04/python-tuya) repository at [https://pypi.python.org/pypi/pytuya](https://pypi.python.org/pypi/pytuya). When there is an update to that repository i upload that change to pypi and increment the version up by one.

**Comment by naylin-mi** [comment]
Well, it still doesn't work for me... Same exact error message.

`2018-01-23 21:41:02 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.living_room_lamp fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/tuya.py", line 76, in update
    status = self._device.status()
  File "/srv/homeassistant/lib/python3.5/site-packages/pytuya/__init__.py", line 257, in status
    result = json.loads(result)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
`
Is it possible that somehow my ha isn't connecting to that pypi and updating or something?

**Comment by slomanl1** [comment]
Sean,
I am confused. I am using hass.io on a Raspberry Pi 3. Is pypi
automatically updated in hass.io, or do I have to use hassbian or some
alternate installation?
Thanks
Larry

**Comment by sean6541** [comment]
Have you restarted hass.io?

**Comment by sean6541** [comment]
Is hass.io up to date? I am also using hass.io on a raspberry pi 3 and have no issues.

**Comment by slomanl1** [comment]
Sean:
I updated hass.io to latest 61.1 last week
Current version 0.61.1
Latest version 0.61.1

Here is what I have done:

Copied tuya.py to custom_components/switch
Restarted hass.io

Here is my log of the error:
2018-01-24 10:09:47 ERROR (MainThread) [homeassistant.helpers.entity]
Update for switch.jaffa_gate fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py",
line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py",
line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/tuya.py", line 78, in update
    self._state = status['dps'][self._switchid]
KeyError: 1

**Comment by naylin-mi** [comment]
I don't use Hass.io, I'm using hassbian. I wouldn't think that it should make much of a difference, should it?

**Comment by slomanl1** [comment]
Naylin,
Are you getting the same error that I am in the thread above? (KeyError: 1)
Larry

**Comment by naylin-mi** [comment]
nope, I'm getting the error that I posted above: 

> TypeError: the JSON object must be str, not 'bytes'

**Comment by slomanl1** [comment]
Naylin,
You should be able to debug better on hassbian. hass.io does not have a
python shell. Have you tried the demo:
https://github.com/clach04/python-tuya

**Comment by naylin-mi** [comment]
To be honest, I looked at it but didn't really know what to do with it. Where to save it to see if it would work or whatever. I'm not real experienced with python or linux overall. :(

**Comment by slomanl1** [comment]
I am not a python person either. I am hoping Sean will help us out and just
get the outlets working with HA. Amazon Alexa does it, IFTTT does it,
SmartLife app does it, so HA should be able to do it.

**Comment by naylin-mi** [comment]
Yes, but all those use the tuya online servers as a go between, it requests from the tuya server to turn on or off and then the server sends the command. This is attempting to circumvent that and turn them on and off directly without ever needing to request from the tuya server. And honestly, that's the biggest reason that I want this to work. My internet can be sketchy sometimes and when it's not working, I can't turn on and off my lights! LOL

**Comment by slomanl1** [comment]
Sean,
I am beginning to think these issues may be device specific.Although they
may be Tuya devices, the protocol may be sightly different for each
mode/manufacturer. I have an idea to potentially isolate the problem: You
could add my device to your HA configuration as I have opened a port on my
PC that forwards to the Rasp Pi using DuckDNS. You can then see if you can
communicated with the device. Let me know if you would like to try.
Thanks
Larry

**Comment by NickSee** [comment]
I'm using Sean's commit 7e5acde with 2 x Tuya Model S2 switches. If I have both  set in Configuration.yaml to id: 1 then the switch config'd second works, the other switch isn't controlled but the slider operates in HA before going back to off after a few seconds.  If I set id: 1 and id: 2 in configuration.yaml, the first switch operates reliably, the second isn't controlled, slider returns to off.  Next to try commenting out the id: config to see if whatever the default is allows both switches to be controlled.  HA info shows 'Error doing job: Task exception was never retrieved
10:38 PM custom_components/switch/tuya.py (ERROR)'

**Comment by NickSee** [comment]
for the record using commit 7e5acde with the id: 1 commented out for both switches works nicely in HA albeit not with any update if something changes in the real world like a switch button is pressed locally.  But it is great to get both working in HA finally, thanks Sean.

**Comment by slomanl1** [comment]
Guys,
I reverted to commit 7e5acde
<https://github.com/sean6541/tuya-homeassistant/commit/7e5acde57aa28802f317961cdfc1f964fcc6d7e3>
with
no id. Finally, I can turn on and off my switch and the slider stays. There
is still a problem: If I flip the switch manually on the device and the
status is not reflected correctly on the slider. This probably means the
device status is not  being polled correctly. Anybody else seen this
behavior?
Larry

**Comment by sean6541** [comment]
I committed 7e5acde just before I started working on status polling, thus commit 7e5acde does not do status polling.

**Comment by slomanl1** [comment]
Sean,
Do you actually have your latest code reliably doing status polling? I just
can't get it to work. It looks like crach04 returns an error anytime status
is requested. Have you looked at his code? Are you handling the error
correctly?
Thanks
Larry

**Comment by sean6541** [comment]
Try using the latest version. There have been some errors fixed in [https://github.com/clach04/python-tuya](https://github.com/clach04/python-tuya)

**Comment by naylin-mi** [comment]
Ok, so, I don't know why, but with this latest version, I can get it to work 100% properly IF I set "id: 1" to each switch in my config file. Id must be 1, nothing else will work. Can't be blank, can't be any other number, can't be commented out, etc... Not that its a bad thing by any means, just wanted to let every one know. I'm extremely happy to have this working now! Thanks so much for all the work that you've been doing.

**Comment by naylin-mi** [comment]
The only thing that sometimes is an issue is that it times out getting status sometimes.

**Comment by naylin-mi** [comment]
Guess I spoke a little too soon. It works great the first time after a restart of homeassistant but then it continuously times out updating the status.

`2018-02-03` 02:33:17 WARNING (MainThread) [homeassistant.components.switch] Updating tuya switch took longer than the scheduled update interval 0:00:30`

**Comment by mikecarr** [comment]
My setup is getting hammed by this, at times I cannot access the frontend.
