### ISSUE TITLE
Multiple Tuya switches

### ISSUE THREAD

**Issue by fryguy04** [sean6541/tuya-homeassistant#10]
First Tuya switch works just fine. I go to add a second and first works, but getting errors on second (as well as the 5 others I added).

Error is: 
`  File "/config/custom_components/switch/tuya.py", line 78, in update
    self._state = status['dps'][self._switchid]
TypeError: byte indices must be integers or slices, not str`

My configuration.yaml file looks like:
`
  - platform: tuya
    name: Tuya1
    host: 10.0.0.171
    local_key: xxxxxxxxxxxxxxxx
    device_id: xxxxxxxxxxxxxxxxxxxx
    id: 1

  - platform: tuya
    name: Tuya2
    host: 10.0.0.172
    local_key: xxxxxxxxxxxxxxxx
    device_id: xxxxxxxxxxxxxxxxxxxx
    id: 1

`

 I installed pytuya and can use the following code to Toggle it so I know Firewall/Key/ID etc works:
`d2 = pytuya.OutletDevice('xxxxxxxxxxxxxxxxxxxx', '10.0.0.172', 'xxxxxxxxxxxxxxxx'); d2.set_status(not  d2.status()['dps']['1'])`

Am I doing something dumb?

**Comment by njloki30** [comment]
Have you tried increaseing the ID: for the 2nd - 5th to id:2, id:3 etc...

**Comment by fryguy04** [comment]
Just tried, didn't work. Thanks for the comment.

Pretty sure `id:` should be `1` signifying first relay per device (if you see current pull request you would increment id when one switch has multiple relays, i have a Tuya 4 port outlet strip this would be useful for) but in my case each Tuya device only controls one load.

I can confirm `id: 1` based on calling pytuya python library directly (from a linux box, can't get at the HomeAssistant code since i'm using the Hassio Docker install ... side note: if anyone knows a way to breakout of the Docker limited view so i can debug I'd be happy to fix this, just too lazy to create an Ubuntu HA install at the moment)

**Comment by fryguy04** [comment]
Ok works now. Didn't change anything but upgraded from 0.65.? to 0.66.1 and now I can control all switches.  For future travelers, here's my configuration.yaml 

    - platform: tuya
      name: Tuya1
      host: 10.0.0.171
      local_key: xxxxxxxxxxxxxxxx
      device_id: xxxxxxxxxxxxxxxxxxxx
      id: 1

    - platform: tuya
      name: Tuya2
      host: 10.0.0.172
      local_key: xxxxxxxxxxxxxxxx
      device_id: xxxxxxxxxxxxxxxxxxxx
      id: 1

**Comment by njloki30** [comment]
I’m having a hard time getting the local key from either wire shark or Charles proxy. The requests appear to be encrypted. I don’t have access to an android device. Any other ways of getting the local key? Or am I missing a step to not have the requests appear to be encrypted in Charles.

Sent from my iPhone

On Apr 8, 2018, at 9:14 PM, fryguy04 <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #10<https://github.com/sean6541/tuya-homeassistant/issues/10>.
