### ISSUE TITLE
It uses the pytuya library confusion

### ISSUE THREAD

**Issue by SDeGonge** [sean6541/tuya-homeassistant#5]
I'm confused about the statement "It uses the pytuya library" in your description.  Do I need to install additional files in addition to the tuya.py file that you provide?  If so, you do I do this? I looked at "https://github.com/clach04/python-tuya" but didn't see any instructions and I'm not that bright when it comes to python/home assistant so any direction would be appreciated.

Thanks

**Comment by sean6541** [comment]
Home Assistant will automatically install the pytuya library. You don't need to install any additional libraries.

**Comment by SDeGonge** [comment]
Can you tell me where to look to verify that it’s installed?  From other posts I read there should be a pytuya folder with an init file located in the components folder.  I do not see this in my setup.

**Comment by charlietomo** [comment]
> Home Assistant will automatically install the pytuya library. You don't need to install any additional libraries.

@sean6541 do you know if the pytuya library still gets installed if HA is installed using hass.io ? Or if not how to install it. Thanks.

**Comment by clach04** [comment]
If the component is installed, required dependencies will be installed at run-time. Closing.
