### ISSUE TITLE
Update for switch fails in Home Assistant

### ISSUE THREAD

**Issue by cmille34** [sean6541/tuya-homeassistant#9]
I bought a couple mini smart socket plugs off Amazon and finally got the localKey and Device ID from the dev_data_storage.xml from a rooted tablet.  I got the switches added to Home Assistant but I am constantly getting the following error and I am only able to actually control the switches like one out of 10 times.  The exact switches I have are:
https://www.amazon.com/gp/product/B075GWQSYH/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

`Update for switch.cheapswitch2 fails
Traceback (most recent call last):
  File "/config/custom_components/switch/tuya.py", line 71, in update
    status = self._device.status()
  File "/config/deps/lib/python3.6/site-packages/pytuya/__init__.py", line 256, in status
    data = self._send_receive(payload)
  File "/config/deps/lib/python3.6/site-packages/pytuya/__init__.py", line 166, in _send_receive
    data = s.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/tuya.py", line 77, in update
    raise ConnectionError("Failed to update status.")
ConnectionError: Failed to update status.`

The full dev_data_storage.xml file is:
`<map>
    <string name="tuya_data">{"deviceRespBeen":[{"activeTime":1521147457,"devId":"02200216ecfabc8124ee","dps":{"1":false,"2":0},"iconUrl":"https://images.tuyaus.com/smart/icon/socket_new2.png","isShare":false,"key":"02200216ecfabc8124ee","lat":"","localKey":"xxxxxxxxxxx","lon":"","moduleMap":{"mcu":{"isOnline":true,"verSw":"1.0.0"},"wifi":{"bv":"5.06","isOnline":true,"pv":"2.1","verSw":"1.0.0"}},"name":"Smart Plug","productId":"ahg3J1WYWKKAWA1L","resptime":1521152340753,"runtimeEnv":"prod","timezoneId":"America/New_York","uuid":"02200216ecfabc8124ee","virtual":false},{"activeTime":1521147457,"devId":"02200216ecfabc87f39d","dps":{"1":false,"2":0},"iconUrl":"https://images.tuyaus.com/smart/icon/socket_new2.png","isShare":false,"key":"02200216ecfabc87f39d","lat":"","localKey":"xxxxxxxxx","lon":"","moduleMap":{"mcu":{"isOnline":true,"verSw":"1.0.0"},"wifi":{"bv":"5.06","isOnline":true,"pv":"2.1","verSw":"1.0.0"}},"name":"Smart Plug 2","productId":"ahg3J1WYWKKAWA1L","resptime":1521152340753,"runtimeEnv":"prod","timezoneId":"America/New_York","uuid":"02200216ecfabc87f39d","virtual":false}],"groupBeen":[],"meshBeen":[{"code":"tymesh1521058915","endTime":0,"key":"meeb7ed74b4f2e1e8c7axt","localKey":"xxxxxxb6","meshId":"meeb7ed74b4f2e1e8c7axt","name":"tymesh1521058915","password":"72dd00aa3ad6d804","pv":"2.1","resptime":1521152340746,"share":false,"startTime":0,"tempShare":false}],"productBeen":[{"attribute":976,"category":"cz","i18nTime":1495524337933,"id":"ahg3J1WYWKKAWA1L","key":"ahg3J1WYWKKAWA1L","meshCategory":"","panelConfig":{},"resptime":1521152340752,"schemaInfo":{"schema":"[{\"mode\":\"rw\",\"code\":\"switch_on\",\"name\":\"开关\",\"property\":{\"type\":\"bool\"},\"iconname\":\"icon-dp_power\",\"id\":1,\"type\":\"obj\",\"desc\":\"\"},{\"mode\":\"rw\",\"code\":\"countdown\",\"name\":\"倒计时\",\"property\":{\"unit\":\"秒\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1,\"type\":\"value\"},\"id\":2,\"type\":\"obj\",\"passive\":true,\"desc\":\"\"}]","schemaExt":"[]","schemaMap":{"1":{"code":"switch_on","iconname":"icon-dp_power","id":"1","mode":"rw","name":"开关","property":"{\"type\":\"bool\"}","schemaType":"bool","type":"obj"},"2":{"code":"countdown","id":"2","mode":"rw","name":"倒计时","passive":true,"property":"{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"unit\":\"秒\"}","schemaType":"value","type":"obj"}}},"shortcut":{"displayDps":[],"displayMsgs":{"dp_switch_on":"Switch","dp_switch_on_off":"Off","dp_switch_on_on":"On","quickop_dp_switch_on":"Switch","quickop_dp_switch_on_off":"Off","quickop_dp_switch_on_on":"On"},"faultDps":[],"quickOpDps":["1"],"switchDp":1},"supportGroup":true,"uiInfo":{"phase":"release","rnFind":true,"type":"RN","ui":"000000004w_1.1.8","uiConfig":{}}}]}</string>
    <string name="tuya_mesh_data">{"meshSubDeviceBean":{"meeb7ed74b4f2e1e8c7axt":[]},"meshSubGroupBean":{}}</string>
</map>`

I've rebooted my tablet so its not trying to open a connection to the switches.  Any idea how I can get these to respond more reliably in Home Assistant?  Anything I am doing wrong?  Any troubleshooting steps you can provide?  Thanks for the help!

**Comment by jpriebe** [comment]
I bought similar plugs: https://www.amazon.com/gp/product/B077VLLKB8/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1

I followed a lot of different instructions before I could get the localKey.   I tried the "Tuya Smart" and "Tuya Smart Life" apps (both oddly similar to one another).  Neither one logged the localKey during pairing.  So I tried the "Jinvoo Smart" app, which also looks similar to the other two (has some of the exact same dialogs -- I suspect there's some shop in China cranking out these crappy apps and whitelabeling them).  Jinvoo *does* log the localKey.  

Anyway, I got the device_id and the local_key.  Then I looked in my router's DHCP leases to find the IP address.

I installed this custom_component (just as easy as the README says) and configured the tuya switch:

```
switch:
  - platform: tuya
    name: Living Room Lamp
    host: 10.0.1.118
    local_key: 8cad5e456b85a559
    device_id: 05200019ecfabc958e4c
```

The switch showed up in the HA interface, but I couldn't control it.  I could ping the IP address, and I could (briefly) connect to port 6668 on the device.  But couldn't turn it on and off.  The UI *sort of* showed me the state of the switch, but it was unreliable.

I increased the HA logger's default level to "debug", and tried again.  Now I could see the error in the logs: 

 ConnectionResetError: [Errno 104] Connection reset by peer

I started thinking maybe there was a conflict between the Jinvoo app and HA.   I uninstalled the Jinvoo app from my phone, and I had full control of the switch!

**Comment by cmille34** [comment]
Ill be darned! I did have the Jinvoo app still installed on my non-rooted tablet and I uninstalled it and restarted HA and it appears that I can control the switches now.  It seems like it takes a couple polls or something for it to get the status but it does appear to be working.  Thanks for pointing me there!
